import { createSlice } from "@reduxjs/toolkit";

export type typeFormData = {
  name: string;
  age: number;
  email: string;
  password: string;
  gender: string;
  acceptTC: boolean;
  picture: string;
  country: { name: string; id: number };
};

export type typeFormDataList = typeFormData[];

export type countriesList = { name: string; id: number }[];

type typeInitState = {
  formData: typeFormDataList;
  countriesList: countriesList;
};
const initialState: typeInitState = {
  formData: [],
  countriesList: [
    { name: "Afghanistan", id: 1 },
    { name: "Albania", id: 2 },
    { name: "Algeria", id: 3 },
    { name: "Andorra", id: 4 },
    { name: "Angola", id: 5 },
    { name: "Antigua and Barbuda", id: 6 },
    { name: "Argentina", id: 7 },
    { name: "Armenia", id: 8 },
    { name: "Australia", id: 9 },
    { name: "Austria", id: 10 },
    { name: "Azerbaijan", id: 11 },
    { name: "Bahamas", id: 12 },
    { name: "Bahrain", id: 13 },
    { name: "Bangladesh", id: 14 },
    { name: "Barbados", id: 15 },
    { name: "Belarus", id: 16 },
    { name: "Belgium", id: 17 },
    { name: "Belize", id: 18 },
    { name: "Benin", id: 19 },
    { name: "Bhutan", id: 20 },
    { name: "Bolivia", id: 21 },
    { name: "Bosnia and Herzegovina", id: 22 },
    { name: "Botswana", id: 23 },
    { name: "Brazil", id: 24 },
    { name: "Brunei", id: 25 },
    { name: "Bulgaria", id: 26 },
    { name: "Burkina Faso", id: 27 },
    { name: "Burundi", id: 28 },
    { name: "Cabo Verde", id: 29 },
    { name: "Cambodia", id: 30 },
    { name: "Cameroon", id: 31 },
    { name: "Canada", id: 32 },
    { name: "Central African Republic", id: 33 },
    { name: "Chad", id: 34 },
    { name: "Chile", id: 35 },
    { name: "China", id: 36 },
    { name: "Colombia", id: 37 },
    { name: "Comoros", id: 38 },
    { name: "Congo (Congo-Brazzaville)", id: 39 },
    { name: "Costa Rica", id: 40 },
    { name: "Cote d'Ivoire", id: 41 },
    { name: "Croatia", id: 42 },
    { name: "Cuba", id: 43 },
    { name: "Cyprus", id: 44 },
    { name: "Czechia (Czech Republic)", id: 45 },
    { name: "Denmark", id: 46 },
    { name: "Djibouti", id: 47 },
    { name: "Dominica", id: 48 },
    { name: "Dominican Republic", id: 49 },
    { name: "Ecuador", id: 50 },
    { name: "Egypt", id: 51 },
    { name: "El Salvador", id: 52 },
    { name: "Equatorial Guinea", id: 53 },
    { name: "Eritrea", id: 54 },
    { name: "Estonia", id: 55 },
    { name: "Eswatini (fmr. 'Swaziland')", id: 56 },
    { name: "Ethiopia", id: 57 },
    { name: "Fiji", id: 58 },
    { name: "Finland", id: 59 },
    { name: "France", id: 60 },
    { name: "Gabon", id: 61 },
    { name: "Gambia", id: 62 },
    { name: "Georgia", id: 63 },
    { name: "Germany", id: 64 },
    { name: "Ghana", id: 65 },
    { name: "Greece", id: 66 },
    { name: "Grenada", id: 67 },
    { name: "Guatemala", id: 68 },
    { name: "Guinea", id: 69 },
    { name: "Guinea-Bissau", id: 70 },
    { name: "Guyana", id: 71 },
    { name: "Haiti", id: 72 },
    { name: "Holy See", id: 73 },
    { name: "Honduras", id: 74 },
    { name: "Hungary", id: 75 },
    { name: "Iceland", id: 76 },
    { name: "India", id: 77 },
    { name: "Indonesia", id: 78 },
    { name: "Iran", id: 79 },
    { name: "Iraq", id: 80 },
    { name: "Ireland", id: 81 },
    { name: "Israel", id: 82 },
    { name: "Italy", id: 83 },
    { name: "Jamaica", id: 84 },
    { name: "Japan", id: 85 },
    { name: "Jordan", id: 86 },
    { name: "Kazakhstan", id: 87 },
    { name: "Kenya", id: 88 },
    { name: "Kiribati", id: 89 },
    { name: "Kuwait", id: 90 },
    { name: "Kyrgyzstan", id: 91 },
    { name: "Laos", id: 92 },
    { name: "Latvia", id: 93 },
    { name: "Lebanon", id: 94 },
    { name: "Lesotho", id: 95 },
    { name: "Liberia", id: 96 },
    { name: "Libya", id: 97 },
    { name: "Liechtenstein", id: 98 },
    { name: "Lithuania", id: 99 },
    { name: "Luxembourg", id: 100 },
    { name: "Madagascar", id: 101 },
    { name: "Malawi", id: 102 },
    { name: "Malaysia", id: 103 },
    { name: "Maldives", id: 104 },
    { name: "Mali", id: 105 },
    { name: "Malta", id: 106 },
    { name: "Marshall Islands", id: 107 },
    { name: "Mauritania", id: 108 },
    { name: "Mauritius", id: 109 },
    { name: "Mexico", id: 110 },
    { name: "Micronesia", id: 111 },
    { name: "Moldova", id: 112 },
    { name: "Monaco", id: 113 },
    { name: "Mongolia", id: 114 },
    { name: "Montenegro", id: 115 },
    { name: "Morocco", id: 116 },
    { name: "Mozambique", id: 117 },
    { name: "Myanmar (formerly Burma)", id: 118 },
    { name: "Namibia", id: 119 },
    { name: "Nauru", id: 120 },
    { name: "Nepal", id: 121 },
    { name: "Netherlands", id: 122 },
    { name: "New Zealand", id: 123 },
    { name: "Nicaragua", id: 124 },
    { name: "Niger", id: 125 },
    { name: "Nigeria", id: 126 },
    { name: "North Korea", id: 127 },
    { name: "North Macedonia (formerly Macedonia)", id: 128 },
    { name: "Norway", id: 129 },
    { name: "Oman", id: 130 },
    { name: "Pakistan", id: 131 },
    { name: "Palau", id: 132 },
    { name: "Palestine State", id: 133 },
    { name: "Panama", id: 134 },
    { name: "Papua New Guinea", id: 135 },
    { name: "Paraguay", id: 136 },
    { name: "Peru", id: 137 },
    { name: "Philippines", id: 138 },
    { name: "Poland", id: 139 },
    { name: "Portugal", id: 140 },
    { name: "Qatar", id: 141 },
    { name: "Romania", id: 142 },
    { name: "Russia", id: 143 },
    { name: "Rwanda", id: 144 },
    { name: "Saint Kitts and Nevis", id: 145 },
    { name: "Saint Lucia", id: 146 },
    { name: "Saint Vincent and the Grenadines", id: 147 },
    { name: "Samoa", id: 148 },
    { name: "San Marino", id: 149 },
    { name: "Sao Tome and Principe", id: 150 },
    { name: "Saudi Arabia", id: 151 },
    { name: "Senegal", id: 152 },
    { name: "Serbia", id: 153 },
    { name: "Seychelles", id: 154 },
    { name: "Sierra Leone", id: 155 },
    { name: "Singapore", id: 156 },
    { name: "Slovakia", id: 157 },
    { name: "Slovenia", id: 158 },
    { name: "Solomon Islands", id: 159 },
    { name: "Somalia", id: 160 },
    { name: "South Africa", id: 161 },
    { name: "South Korea", id: 162 },
    { name: "South Sudan", id: 163 },
    { name: "Spain", id: 164 },
    { name: "Sri Lanka", id: 165 },
    { name: "Sudan", id: 166 },
    { name: "Suriname", id: 167 },
    { name: "Sweden", id: 168 },
    { name: "Switzerland", id: 169 },
    { name: "Syria", id: 170 },
    { name: "Tajikistan", id: 171 },
    { name: "Tanzania", id: 172 },
    { name: "Thailand", id: 173 },
    { name: "Timor-Leste", id: 174 },
    { name: "Togo", id: 175 },
    { name: "Tonga", id: 176 },
    { name: "Trinidad and Tobago", id: 177 },
    { name: "Tunisia", id: 178 },
    { name: "Turkey", id: 179 },
    { name: "Turkmenistan", id: 180 },
    { name: "Tuvalu", id: 181 },
    { name: "Uganda", id: 182 },
    { name: "Ukraine", id: 183 },
    { name: "United Arab Emirates", id: 184 },
    { name: "United Kingdom", id: 185 },
    { name: "United States of America", id: 186 },
    { name: "Uruguay", id: 187 },
    { name: "Uzbekistan", id: 188 },
    { name: "Vanuatu", id: 189 },
    { name: "Venezuela", id: 190 },
    { name: "Vietnam", id: 191 },
    { name: "Yemen", id: 192 },
    { name: "Zambia", id: 193 },
    { name: "Zimbabwe", id: 194 },
  ],
};

export const formSlice = createSlice({
  name: "form",
  initialState,
  reducers: {
    submitForm: (state, action) => {
      state.formData.push(action.payload);
    },
  },
});

export const { submitForm } = formSlice.actions;
